{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "env": {
    "es6": true,
    "browser": true,
    "node": true,
    "jest": true,
    "jasmine": true
  },
  "rules": {
    "@typescript-eslint/no-unused-vars": "off",
    "no-unused-vars": "off",
    "no-useless-constructor": "off",
    "@typescript-eslint/no-useless-constructor": [ "off" ]
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "modules": true
    }
  }
}
