name: Create && Deploy

on:
  push:
    branches:
      - master
      - develop
    tags-ignore:
      - '*'

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  DOCKER_USERNAME: "_"
  DOCKER_TOKEN: ${{ secrets.HEROKU_API_KEY }}
  PROJECT: ${{ secrets.PROJECT }}
  TAG_MANAGER: ${{ secrets.TAG_MANAGER }}

  WORKING_GROUP: "" # Working group list
  MEMBERSHIP: "" # Address membership contract
  INTERHACK: "" # Address interhack contract
  WEB3: "" # Address web3 contract
  DISRUPTIVE: "" # Address disruptive contract
  VOTINGS: "" # Address voting contract

  DISRUPTIVE_ISSUE_TEMPLATE: ${{ secrets.DISRUPTIVE_ISSUE_TEMPLATE }}
  VOTINGS_ISSUE_TEMPLATE: ${{ secrets.VOTINGS_ISSUE_TEMPLATE }}
  INTERHACK_ISSUE_TEMPLATE: ${{ secrets.INTERHACK_ISSUE_TEMPLATE }}
  WEB3_ISSUE_TEMPLATE: ${{ secrets.WEB3_ISSUE_TEMPLATE }}

  GRANT_PROGRAM_LINK: ${{ secrets.GRANT_PROGRAM_LINK }}
  DISRUPTIVE_ABOUT_LINK: $${{ secrets.DISRUPTIVE_ABOUT_LINK }}
  VOTINGS_ABOUT_LINK: ${{ secrets.VOTINGS_ABOUT_LINK }}
  WEB3_ABOUT_LINK: ${{ secrets.WEB3_ABOUT_LINK }}
  INTERHACK_ABOUT_LINK: ${{ secrets.INTERHACK_ABOUT_LINK }}

jobs:

  create:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables for environment
        uses: ./.github/set-env/
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Create heroku application
        uses: ./.github/heroku-create/
        with:
          project: ${{ env.PROJECT }}-${GITHUB_REF##*/}
          label: "Waves Association DAO"

  build:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables for environment
        uses: ./.github/set-env/
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Set ENV
        run: echo "HEROKU_APPLICATION=$PROJECT-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set config
        uses: mshick/fast-envsubst@v1
        with:
          in-file: ./projects/dapp/src/environments/environment.prod.ts
          out-file: ./projects/dapp/src/environments/environment.prod.ts

      - name: Set analytics
        uses: mshick/fast-envsubst@v1
        with:
          in-file: ./projects/dapp/src/index.html
          out-file: ./projects/dapp/src/index.html

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: registry.heroku.com/${{ env.HEROKU_APPLICATION }}/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables for environment
        uses: ./.github/set-env/
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Set ENV
        run: echo "HEROKU_APPLICATION=${{ env.PROJECT }}-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Release
        run: |
          heroku container:release web -a $HEROKU_APPLICATION
