name: Create && Deploy

on: push

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  DOCKER_USERNAME: "_"
  DOCKER_TOKEN: ${{ secrets.HEROKU_API_KEY }}
  PROJECT: ${{ secrets.PROJECT }}
  CONFIG: ${{ secrets.CONFIG }}

  MEMBERSHIP: ${{ secrets.MEMBERSHIP }}
  DISRUPTIVE: ${{ secrets.DISRUPTIVE }}
  WEB3: ${{ secrets.WEB3 }}
  INTERHACK: ${{ secrets.INTERHACK }}

  DISRUPTIVE_ISSUE_TEMPLATE: ${{ secrets.DISRUPTIVE_ISSUE_TEMPLATE }}
  WEB3_ISSUE_TEMPLATE: ${{ secrets.WEB3_ISSUE_TEMPLATE }}
  INTERHACK_ISSUE_TEMPLATE: ${{ secrets.WEB3_ISSUE_TEMPLATE }}

  GRANT_PROGRAM_LINK: ${{ secrets.WEB3_ISSUE_TEMPLATE }}

  WORKING_GROUP: ${{ secrets.secrets.WORKING_GROUP }}

jobs:
  create:
    runs-on: ubuntu-latest
    if: contains( github.ref, 'refs/tags/') == false
    continue-on-error: true
    steps:
      - name: Set ENV
        run: |
          echo "HEROKU_APPLICATION_BASE=${{ env.PROJECT }}-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create an applications if it does not exist
        continue-on-error: true
        run: |
          heroku create ${HEROKU_APPLICATION_BASE}

      - name: Set env to heroku server
        run: |
          heroku config:set \
            LABEL="Waves Association DAO. $HEROKU_APPLICATION_BASE" \
            -a $HEROKU_APPLICATION_BASE

  build:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Set ENV
        run: echo "HEROKU_APPLICATION=$PROJECT-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: registry.heroku.com/${{ env.HEROKU_APPLICATION }}/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set ENV
        run: echo "HEROKU_APPLICATION=${{ env.PROJECT }}-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Release
        run: |
          heroku container:release web -a $HEROKU_APPLICATION
