name: Deploy waves contracts

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

env:
  # Use secrets after set environment
  WD_MEMBERSHIP_ADDRESS: ""
  WD_MEMBERSHIP_SEED: ""
  WD_DEPOSIT_SEED: ""
  WD_DISRUPTIVE_SEED: ""
  WD_INTERHACK_SEED: ""
  WD_VOTINGS_SEED: ""
  WD_WEB3_SEED: ""

jobs:
  develop:
    name: Update develop contracts
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    environment: 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables for environment
        uses: ./.github/set-env/
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Apply environment on config
        run: |
          npx envsub ./contracts/develop.json

      - name: Waves deployer
        uses: rieset/waves-deployer@v.1.1.0
        id: deploy
        with:
          config: './contracts/develop.json'

      - name: Output data
        run: |
          echo "${{ steps.deploy.outputs.contracts }}" >> ./contracts.json

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: contracts
          path: ./contracts.json

  testing:
    name: Deploy new temporary contracts
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'
    environment: 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables for environment
        uses: ./.github/set-env/
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Apply environment on config
        run: |
          npx envsub ./contracts/testing.json

      - name: Waves deployer
        uses: rieset/waves-deployer@v.1.1.0
        id: deploy
        with:
          config: './contracts/testing.json'

      - name: Output data
        run: |
          echo "${{ steps.deploy.outputs.contracts }}" >> ./contracts.json

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: contracts
          path: ./contracts.json
