name: Publish latest packages

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

env:
  # Base options
  PACKAGE_NAME: ${{ github.event.repository.name }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

  # Github options
  GHCR_REGISTRY_OWNER: ${{ github.repository_owner }}
  GHCR_REGISTRY_HOST: ghcr.io
  GHCR_REGISTRY_USERNAME: ${{ secrets.PACKAGES_USER }}
  GHCR_REGISTRY_PASSWORD: ${{ secrets.PACKAGES_TOKEN }}

jobs:

  create-latest-image:
    environment: 'production'
    name: Create latest docker image
    runs-on: ubuntu-latest
    if: contains( github.ref, 'refs/tags/') == false && github.ref == 'refs/heads/packages'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set variables for environment
        uses: ./.github/set-env/
        with:
          secrets: ${{ toJSON(secrets) }}

      -
        name: Create tag image
        run: |
          echo "IMAGE_TAG_NAME=${{ env.GHCR_REGISTRY_HOST }}/${GITHUB_REPOSITORY,,}:latest" >> ${GITHUB_ENV}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -

        name: Login to GithHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_REGISTRY_HOST }}
          username: ${{ env.GHCR_REGISTRY_USERNAME }}
          password: ${{ env.GHCR_REGISTRY_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_TAG_NAME }}
